### ISSUE TITLE
Provide a static abstract interface method to register endpoints

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/MinimalHelpers#20]
Currently, the library requires that we implement the [IEndpointRouteHandler](https://github.com/marcominerva/MinimalHelpers.Routing/blob/master/src/MinimalHelpers.Routing/IEndpointRouteHandler.cs) interface and, at runtime, reflection is used to instantiate the class in order to call the `MapEndpoints` method. With **.NET 7.0**, we can provide an alternative method to endpoint registration using [static abstract interface members](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/static-virtual-interface-members). The proposal is to add the following interface and the corresponding extension method to the library:

```
public interface IStaticEndpointRouteHandler
{
    static abstract void MapEndpoints(IEndpointRouteBuilder endpoints);
}

public static void MapEndpoints<T>(this IEndpointRouteBuilder endpoints) where T : IStaticEndpointRouteHandler
{
     // ...
}
```

In this way, we can register our handler using a syntax like this:

```
app.MapEndpoints<PeopleHandler>();
app.MapEndpoints<ProductsHandler>();
```

And no reflection at all will be involved in the registration process.

The question is: giving this new behavior, do you think that `IStaticEndpointRouteHandler` is a good name for the new interface?

**Comment by davidfowl** [comment]
It should return an `IEndpointConventionBuilder`. I also don't like the name static or the fact that it is a "RouteHandler", it's more of a things that registers route handlers than a route handler itself.

**Comment by marcominerva** [comment]
Hi @davidfowl, thank you for your comment! So, what name do you suggest for this interface?
